{% set python_min = '3.10' %}
{% set name = "gps-timemachine" %}
{% set version = "1.1.5" %}


package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gps_timemachine-{{ version }}.tar.gz
  sha256: 7758810c5417e2f7a80834d422d01f55f05709897bd06df107f19d2f8c896fa7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - gps_timemachine.gps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://bitbucket.org/nsidc/gps-timemachine
  license: MIT
  license_file: LICENSE
  summary: Adjust GPS datetimes to UTC.


extra:
  recipe-maintainers:
    - trey-stafford
    - mfisher87
